function [BW,maskedImage] = segmentCaudateWithBiggerSpots(X)
%segmentImage Segment image using auto-generated code from imageSegmenter App
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter App. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 16-Aug-2016
%----------------------------------------------------


% Normalize input data to range in [0,1].
Xmin = min(X(:));
Xmax = max(X(:));
X = (X - Xmin) ./ (Xmax - Xmin);

% Create empty mask.
BW = false(size(X));

% Flood fill
row = 12;
column = 22;
tolerance = 1.000000e-02;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Rectangle drawing
xPos = [22.7998 25.0980 25.0980 22.7998];
yPos = [8.0745 8.0745 9.0126 9.0126];
m = size(BW, 1);
n = size(BW, 2);
addedRegion = poly2mask(xPos, yPos, m, n);
BW = BW | addedRegion;

% Flood fill
row = 11;
column = 10;
tolerance = 1.000000e-02;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Rectangle drawing
xPos = [22.6591 25.1449 25.1449 22.6591];
yPos = [7.6524 7.6524 9.1533 9.1533];
m = size(BW, 1);
n = size(BW, 2);
addedRegion = poly2mask(xPos, yPos, m, n);
BW = BW | addedRegion;

% Rectangle drawing
xPos = [23.7848 25.2856 25.2856 23.7848];
yPos = [9.7161 9.7161 12.1549 12.1549];
m = size(BW, 1);
n = size(BW, 2);
addedRegion = poly2mask(xPos, yPos, m, n);
BW = BW | addedRegion;

% Rectangle drawing
xPos = [21.9556 23.1281 23.1281 21.9556];
yPos = [8.7312 8.7312 9.2940 9.2940];
m = size(BW, 1);
n = size(BW, 2);
addedRegion = poly2mask(xPos, yPos, m, n);
BW = BW | addedRegion;

% Rectangle drawing
xPos = [20.7831 21.8149 21.8149 20.7831];
yPos = [14.8283 14.8283 16.0946 16.0946];
m = size(BW, 1);
n = size(BW, 2);
addedRegion = poly2mask(xPos, yPos, m, n);
BW = BW | addedRegion;

% Rectangle drawing
xPos = [10.8400 13.2789 13.2789 10.8400];
yPos = [14.9690 14.9690 16.2353 16.2353];
m = size(BW, 1);
n = size(BW, 2);
addedRegion = poly2mask(xPos, yPos, m, n);
BW = BW | addedRegion;

% Freehand drawing
xPos = [9.1516 9.3392 9.3861 9.4330 9.4799 9.6206 9.7613 9.8551 9.9489 9.9958 9.9958 10.0427 10.0896 10.1365 10.1834 10.1834 10.2303 10.2303 10.2772 10.2772 10.2772 10.3710 10.4179 10.4648 10.5117 10.5586 10.5586 10.5586 10.5586 10.5586 10.5586 10.5586 10.5586 10.5586 10.5117 10.5117 10.4648 10.4179 10.3710 10.3241 10.2772 10.2772 10.2303 10.1834 10.1834 10.1365 10.0896 9.9958 9.9020 9.8082 9.7144 9.6675 9.6206 9.5737 9.5268 9.4799 9.4330 9.3861 9.3861 9.3861 9.3861 9.3861 9.3861 9.3861 9.3861 9.3861 9.3861 9.3861 9.3861 9.3861 9.3861 9.3861 9.3861 9.3861 9.3861 9.3861 9.3861 9.3861 9.3861 9.3861 9.3861 9.3861 9.3392 9.3392 9.3392 9.2923 9.2923 9.2923 9.2454 9.2454 9.2454];
yPos = [10.7010 10.7010 10.7010 10.7010 10.7479 10.8417 10.9355 10.9824 11.0293 11.0762 11.1231 11.1700 11.2169 11.2638 11.3107 11.3576 11.3576 11.4045 11.4045 11.4514 11.4983 11.4983 11.5921 11.6390 11.6390 11.6859 11.7328 11.7797 11.8266 11.8735 11.9204 11.9673 12.0142 12.0611 12.0611 12.1080 12.1549 12.1549 12.1549 12.1549 12.1549 12.2018 12.2487 12.2956 12.3425 12.3425 12.3425 12.3894 12.3894 12.4363 12.4363 12.4363 12.4363 12.4363 12.4363 12.3894 12.3425 12.3425 12.2956 12.2487 12.2018 12.1549 12.1080 12.0611 12.0142 11.9673 11.9204 11.8735 11.8266 11.7797 11.7328 11.6859 11.6390 11.5921 11.5452 11.4983 11.4514 11.3576 11.3107 11.2638 11.2169 11.1700 11.0762 11.0293 10.9824 10.9355 10.8886 10.8417 10.8417 10.7948 10.7479];
m = size(BW, 1);
n = size(BW, 2);
addedRegion = poly2mask(xPos, yPos, m, n);
BW = BW | addedRegion;

% Rectangle drawing
xPos = [10.0427 12.2471 12.2471 10.0427];
yPos = [10.0444 10.0444 11.0293 11.0293];
m = size(BW, 1);
n = size(BW, 2);
addedRegion = poly2mask(xPos, yPos, m, n);
BW = BW | addedRegion;

% Rectangle drawing
xPos = [10.3710 12.3878 12.3878 10.3710];
yPos = [9.7630 9.7630 10.7948 10.7948];
m = size(BW, 1);
n = size(BW, 2);
addedRegion = poly2mask(xPos, yPos, m, n);
BW = BW | addedRegion;

% Rectangle drawing
xPos = [10.2772 13.4665 13.4665 10.2772];
yPos = [10.3727 10.3727 11.2169 11.2169];
m = size(BW, 1);
n = size(BW, 2);
addedRegion = poly2mask(xPos, yPos, m, n);
BW = BW | addedRegion;

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;