function [BW,maskedImage] = segmentBigColdSpot(X)
%segmentImage Segment image using auto-generated code from imageSegmenter App
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter App. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 16-Aug-2016
%----------------------------------------------------


% Normalize input data to range in [0,1].
Xmin = min(X(:));
Xmax = max(X(:));
X = (X - Xmin) ./ (Xmax - Xmin);

% Create empty mask.
BW = false(size(X));

% Polygon drawing
xPos = [23.2688 23.1750 22.5184 21.6273];
yPos = [11.1700 9.7630 10.7010 10.8417];
m = size(BW, 1);
n = size(BW, 2);
addedRegion = poly2mask(xPos, yPos, m, n);
BW = BW | addedRegion;

% Rectangle drawing
xPos = [21.8618 23.0812 23.0812 21.8618];
yPos = [10.6541 10.6541 11.4045 11.4045];
m = size(BW, 1);
n = size(BW, 2);
addedRegion = poly2mask(xPos, yPos, m, n);
BW = BW | addedRegion;

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;