function [BW,maskedImage] = segmentBigColdSpot_highres(X)
%segmentImage Segment image using auto-generated code from imageSegmenter App
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter App. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 13-Oct-2016
%----------------------------------------------------


% Create empty mask.
BW = false(size(X));

% Flood fill
row = 43;
column = 96;
tolerance = 3276;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;