function [BW,maskedImage] = segmentCaudate(X)
%segmentImage Segment image using auto-generated code from imageSegmenter App
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter App. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 16-Aug-2016
%----------------------------------------------------


% Normalize input data to range in [0,1].
Xmin = min(X(:));
Xmax = max(X(:));
X = (X - Xmin) ./ (Xmax - Xmin);

% Create empty mask.
BW = false(size(X));

% Flood fill
row = 12;
column = 9;
tolerance = 3.000000e-02;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 12;
column = 22;
tolerance = 1.000000e-02;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Freehand drawing
xPos = [22.8301];
yPos = [10.0387];
m = size(BW, 1);
n = size(BW, 2);
addedRegion = poly2mask(xPos, yPos, m, n);
BW = BW | addedRegion;

% Rectangle drawing
xPos = [22.4075 24.4268 24.4268 22.4075];
yPos = [9.9448 9.9448 10.0856 10.0856];
m = size(BW, 1);
n = size(BW, 2);
addedRegion = poly2mask(xPos, yPos, m, n);
BW = BW | addedRegion;

% Freehand drawing
xPos = [24.2390 24.4268 24.5677 24.7086 24.8964 25.0373 25.1782 25.2721 25.3191 25.4130 25.4599 25.5069 25.5539];
yPos = [7.9724 7.9724 7.9724 7.9724 7.9724 7.9724 8.0193 8.0193 8.0663 8.0663 8.0663 8.0663 8.0663];
m = size(BW, 1);
n = size(BW, 2);
addedRegion = poly2mask(xPos, yPos, m, n);
BW = BW | addedRegion;

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;