function make_mhdr(ObjData,filename)

[~,Name] = fileparts(filename);

fid = fopen(filename,'w');
fprintf(fid,'%s\n','!INTERFILE:=',...
    '%comment:=SMS-MI sinogram common attributes',...
    '!originating system:=2008',...
    '%SMS-MI header name space:=sinogram main header',...
    '%SMS-MI version number:=3.1',...
    '!GENERAL DATA:=',...
    'data description:=sinogram',...
    'exam type:=wholebody',...
    '%study date (yyyy:mm:dd):=2016:03:23',...
    '%study time (hh:mm:ss GMT+00:00):=15:33:29',...
    '%type of detector motion:=step and shoot',...
    '%DATA MATRIX DESCRIPTION:=',...
    'number of time frames:=1',...
    '%number of horizontal bed offsets:=1',...
    'number of time windows:=1',...
    '%number of emission data types:=2',...
    '%emission data type description [1]:=prompts',...
    '%emission data type description [2]:=randoms',...
    '%number of transmission data types:=0',...
    '%scan direction:=in',...
    '%DATA SET DESCRIPTION:=',...
    '!total number of data sets:=1' );
fprintf(fid,'%%data set [1]:={30,%s.s.hdr,UNKNOWN}\n',Name);
fclose(fid);
end

